name: plantit
description: plant trees

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  lottie: ^1.4.3
  flutter_launcher_icons: ^0.10.0
  theme_mode_builder: ^1.0.2
  bottom_navy_bar: ^6.0.0
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.0.3
  cached_network_image: ^3.2.2
  line_icons: ^2.0.1
  get: ^4.6.5
  http: ^0.13.5

  location: ^4.4.0
  google_maps: ^6.2.0
  google_maps_flutter: ^2.2.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  unicons: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
